// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9SgImtgBKQnDwAHMU1g2hvIjxxLz6IBA',
    appId: '1:278467875304:android:90dbddbefefd7bcf1f145d',
    messagingSenderId: '278467875304',
    projectId: 'equicare-52e84',
    databaseURL: 'https://equicare-52e84.firebaseio.com',
    storageBucket: 'equicare-52e84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3AmW205vbiDH05aL9n879ZRI05HTJmno',
    appId: '1:278467875304:ios:34143a2056d492cb1f145d',
    messagingSenderId: '278467875304',
    projectId: 'equicare-52e84',
    databaseURL: 'https://equicare-52e84.firebaseio.com',
    storageBucket: 'equicare-52e84.appspot.com',
    androidClientId:
        '278467875304-0m4irfp11q5tdbmtdism5790mlf0keqr.apps.googleusercontent.com',
    iosClientId:
        '278467875304-andgheraafkpavvqj0s9dnkpfo1feuu4.apps.googleusercontent.com',
    iosBundleId: 'com.supportsoft.equicare',
  );
}
